/*
 * GenerateDictionary.java
 * Copyright (C) 2026 Chris Burdess
 *
 * This file is part of micula, a Brotli codec for Java.
 * For more information please visit https://github.com/cpkb-bluezoo/micula/
 *
 * micula is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * micula is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with micula.  If not, see <http://www.gnu.org/licenses/>.
 */

import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;

/**
 * Build-time tool: reads dictionary.bin and emits DictionaryData.java
 * containing a static byte array. No java.io.InputStream/OutputStream.
 *
 * Usage: GenerateDictionary &lt;dictionary.bin&gt; &lt;DictionaryData.java&gt;
 *
 * @author <a href="mailto:dog@gnu.org">Chris Burdess</a>
 */
public class GenerateDictionary {

    private static final int EXPECTED_SIZE = 122784;

    public static void main(String[] args) throws Exception {
        if (args.length != 2) {
            System.err.println("Usage: GenerateDictionary <dictionary.bin> <DictionaryData.java>");
            System.exit(1);
        }
        Path inPath = Paths.get(args[0]);
        Path outPath = Paths.get(args[1]);

        FileChannel in = FileChannel.open(inPath, StandardOpenOption.READ);
        ByteBuffer buf = ByteBuffer.allocate(EXPECTED_SIZE);
        int total = 0;
        while (total < EXPECTED_SIZE) {
            int n = in.read(buf);
            if (n < 0) {
                break;
            }
            total += n;
        }
        in.close();
        if (total != EXPECTED_SIZE) {
            throw new IllegalStateException(
                "Expected dictionary size " + EXPECTED_SIZE + ", got " + total);
        }
        byte[] data = buf.array();

        StringBuilder sb = new StringBuilder(EXPECTED_SIZE * 6 + 2000);
        sb.append("/*\n");
        sb.append(" * DictionaryData.java\n");
        sb.append(" * Copyright (C) 2026 Chris Burdess\n");
        sb.append(" *\n");
        sb.append(" * This file is part of micula, a Brotli codec for Java.\n");
        sb.append(" * GENERATED by tools/GenerateDictionary.java — do not edit.\n");
        sb.append(" * Dictionary bytes are from RFC 7932 Appendix A.\n");
        sb.append(" *\n");
        sb.append(" * micula is free software: you can redistribute it and/or modify\n");
        sb.append(" * it under the terms of the GNU Lesser General Public License as published by\n");
        sb.append(" * the Free Software Foundation; either version 2.1 of the License, or\n");
        sb.append(" * (at your option) any later version.\n");
        sb.append(" */\n");
        sb.append("\n");
        sb.append("package org.bluezoo.micula;\n");
        sb.append("\n");
        sb.append("/**\n");
        sb.append(" * Embedded RFC 7932 static dictionary (122,784 bytes).\n");
        sb.append(" * Generated at build time from resources/dictionary.bin.\n");
        sb.append(" *\n");
        sb.append(" * @author <a href=\"mailto:dog@gnu.org\">Chris Burdess</a>\n");
        sb.append(" */\n");
        sb.append("final class DictionaryData {\n");
        sb.append("\n");
        sb.append("    static final byte[] BYTES;\n");
        sb.append("\n");
        sb.append("    static {\n");
        sb.append("        BYTES = new byte[").append(EXPECTED_SIZE).append("];\n");
        // Split fills across methods so no single method exceeds the 64KiB bytecode limit
        int methodSize = 4096; // bytes of dictionary per fill method
        int methodCount = (EXPECTED_SIZE + methodSize - 1) / methodSize;
        for (int m = 0; m < methodCount; m++) {
            sb.append("        fill").append(m).append("(BYTES);\n");
        }
        sb.append("    }\n");
        sb.append("\n");

        int offset = 0;
        for (int m = 0; m < methodCount; m++) {
            int end = Math.min(offset + methodSize, EXPECTED_SIZE);
            sb.append("    private static void fill").append(m).append("(byte[] dest) {\n");
            while (offset < end) {
                int chunk = Math.min(64, end - offset);
                sb.append("        put(dest, ").append(offset).append(",");
                for (int i = 0; i < chunk; i++) {
                    if (i > 0) {
                        sb.append(',');
                    }
                    sb.append("(byte)").append(data[offset + i]);
                }
                sb.append(");\n");
                offset += chunk;
            }
            sb.append("    }\n");
            sb.append("\n");
        }

        sb.append("    private static void put(byte[] dest, int offset, byte... values) {\n");
        sb.append("        System.arraycopy(values, 0, dest, offset, values.length);\n");
        sb.append("    }\n");
        sb.append("\n");
        sb.append("    private DictionaryData() {\n");
        sb.append("    }\n");
        sb.append("}\n");

        byte[] outBytes = sb.toString().getBytes(StandardCharsets.UTF_8);
        FileChannel out = FileChannel.open(outPath,
            StandardOpenOption.CREATE,
            StandardOpenOption.TRUNCATE_EXISTING,
            StandardOpenOption.WRITE);
        ByteBuffer outBuf = ByteBuffer.wrap(outBytes);
        while (outBuf.hasRemaining()) {
            out.write(outBuf);
        }
        out.close();
    }
}
